name: spring-boot-app-with-mysql
services:
  spring-app:
    container_name: spring-app
    image: hello-spring-boot-app:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shudong_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - springboot-mysql-network
    depends_on:
      - mysql
  mysql:
    container_name: docker-mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=shudong_db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-network
volumes:
  mysql-data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network